### ISSUE TITLE
How to deal with sizefull?

### ISSUE THREAD

**Issue by amahdy** [vaadin/board#77]
`1.0.0-alpha5`

Here is the code:

```java
        CssLayout l1 = new CssLayout();
        l1.addStyleName("red");
        l1.setSizeFull();
        CssLayout l2 = new CssLayout();
        l2.addStyleName("blue");
        l2.setSizeFull();

        Board b = new Board();
        b.addRow(l1, l2).setSizeFull();
        b.setSizeFull();

        setContent(b);
```

And theme:

```css
  .red {
    background-color: red;
  }

  .blue {
    background-color: blue;
  }
```

When screen size is small enough, `l2` disappears totally.
